### ISSUE TITLE
Backend menu page getting 400 error

### ISSUE THREAD

**Issue by tushar-baldha** [OliveStudio/olivemenus#40]
admin/olivemenus/
this url not working, getting "Missing required parameters: siteHandle" error on backend

**Comment by vanburenx** [comment]
Seeing the same issue after v1.1.8 upgrade.

**System Information** 
- PHP version	7.2.30
- OS version	Linux 4.4.0-178-generic
- Database driver & version	PostgreSQL 9.5.21
- Craft edition & version	Craft Solo 3.4.18
- Olivemenus	1.1.8

**Stack Trace**
```
yii\web\BadRequestHttpException: Missing required parameters: siteHandle in REPLACE_WITH_PATH/vendor/yiisoft/yii2/web/Controller.php:173
Stack trace:
#0 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\web\Controller->bindActionParams(Object(yii\base\InlineAction), Array)
#1 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#2 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('', Array)
#3 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('', Array)
#4 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('olivemenus/menu', Array)
#5 REPLACE_WITH_PATH/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('olivemenus/menu', Array)
#6 REPLACE_WITH_PATH/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#7 REPLACE_WITH_PATH/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 REPLACE_WITH_PATH/web/index.php(21): yii\base\Application->run()
#9 /home/vmlocal/.composer/vendor/cpriego/valet-linux/server.php(232): require('/home/vmlocal/a...')
#10 {main}
```

**Comment by matthewstick** [comment]
seeing this issue as well

**Comment by japo32** [comment]
Same here.

**Comment by developer-murtazavhora** [comment]
Same here

**Comment by tushar-baldha** [comment]
this issue only version 1.1.8
I have downgrade version 1.1.6 and working fine :)

**Comment by alinistrate** [comment]
Hello,

We are looking into this issue and will push a fix. If anyone can do a pull request and fix it that would be helpful. We don't have the resources available now to do it.

Thanks,
Alin

**Comment by niektenhoopen** [comment]
@alinistrate This is the same as #43 and should be solved in the latest version.

**Comment by alinistrate** [comment]
I will close this out. 
Thank you all!
